### PR TITLE
Fix clearAllEvents() method by correct emptying of custom api events

### PR DESCRIPTION
**Pull request by lysyi3m**
Fixes https://github.com/biati-digital/glightbox/issues/175

### CODE REVIEW

**Comment by lysyi3m** [comment]
@biati-digital any chances we got this reviewed soon?

**Comment by biati-digital** [comment]
@lysyi3m Sorry, probably this weekend, there's currently a lot of work but hopefully i'll have some time this weekend to publish an update.

**Comment by lysyi3m** [comment]
@biati-digital is there new npm release with this? Sorry, I can find only git tag for v3.0.6

**Comment by biati-digital** [comment]
it should be ready on npm :)

**Pull request merged**
