### PR TITLE
Fix z-index on firefox thinking it's a hex value

### PR DESCRIPTION
**Pull request by mynameisbogdan**
Hello,

Firefox (88 at least) seems to think `z-index: 999999 !important` it's `z-index: #999 !important`.

Adding an extra digit seems to fix it.

Screenshot 2021-05-20 at 01 54 36

### CODE REVIEW

**Comment by frankie-tech** [comment]
Hey there @mynameisbogdan,

Thanks for filing this PR!

Looks like we got ourselves a genuine browser bug. Looking through [Bugzilla](https://bugzilla.mozilla.com), I can't find a report. It would be worth it to add your findings there.

I'll pin an issue mentioning this PR, since it is *weird*. 

These three lines seem to be all you need for a hot patch.

```css
.glightbox-container {
    z-index: 9999999 !important;
}
```

**Comment by biati-digital** [comment]
CleanShot 2021-05-20 at 01 17 16

I'm not able to see the error you mention in Firefox 88, also tested with Firefox developer edition 88 and it looks good. I'm using Mac OS Big Sur maybe you are using another OS?

CleanShot 2021-05-20 at 01 07 22

I was not able to find anything about similar issues on Google so this is really weird.

**Comment by mynameisbogdan** [comment]
Hello @biati-digital,

I'm using 88.0.1 on Mojave. 

The bug it's only when it's fist loaded by the browser. Editing it in developer tools adds the corect value.

**Comment by biati-digital** [comment]
I use Edge as my every day browser, firefox developer edition only for certain tests, and the regular firefox was a clean install as i do not use it. In both cases i just simply launched firefox entered the url and opened the developer tools and you can see in the screenshots what i saw.

Anyway, i do not mind the extra digit if it fixes a possible and weird issue, v4 will change drastically the CSS so we can add this as a temporary fix for now.

**Comment by biati-digital** [comment]
@frankie-tech are you able to replicate this issue?

**Comment by mynameisbogdan** [comment]
@frankie-tech @biati-digital I just took a look at the dist files bundled by webpack and it seems like it's not a browser bug.

The culprit seems to be `css-minimizer-webpack-plugin`  which outputs `z-index: 999999 !important` as `z-index:#999!important` when using the default preset. (using `cssnano-preset-simple` the output is correct)

I'll report this to them.

Thank you for your time.

**Pull request closed without merging**
