### PR TITLE
fix(video.js): extend provider regex for ytb shorts

### LINKED ISSUE #395: YouTube Shorts
I find that the videos don't play when YouTube Shorts URL is provided. Can someone guide me to fix it?

Thanks,
Leena

### PR DESCRIPTION
**Pull request by tomasvn**
- [Closes #395](https://github.com/biati-digital/glightbox/issues/395)
- Coudn't test it localy as youtube returned error 
```Refused to display 'https://www.youtube.com/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.```

### CODE REVIEW

**Comment by tomasvn** [comment]
@gingerchew Were you able to review my PR?

**Comment by gingerchew** [comment]
It looks good to me!

**Comment by tomasvn** [comment]
bump

**Comment by Lefthandmedia** [comment]
merge please

**Pull request merged**
